/**
 * Phase 3: Add materias for all cargos
 *
 * This script adds standard materias to all cargos based on their type:
 * - Police/Security: Português, Raciocínio Lógico, Informática, Dir. Constitucional, Dir. Administrativo, Dir. Penal
 * - Military: Português, Matemática, Geografia, História, Física
 * - Administrative: Português, Raciocínio Lógico, Informática, Dir. Constitucional, Dir. Administrativo
 */

import "dotenv/config";
import { db } from "./index";
import { sql } from "drizzle-orm";

// Standard materia sets
const MATERIAS_BASE = {
  // Common to all
  PORTUGUES: { nome: "Língua Portuguesa", codigo: "PORTUGUES", ordem: 1 },
  RACIOCINIO_LOGICO: { nome: "Raciocínio Lógico", codigo: "RACIOCINIO_LOGICO", ordem: 2 },
  INFORMATICA: { nome: "Noções de Informática", codigo: "INFORMATICA", ordem: 3 },
  MATEMATICA: { nome: "Matemática", codigo: "MATEMATICA", ordem: 2 },

  // Direito
  DIREITO_CONSTITUCIONAL: { nome: "Direito Constitucional", codigo: "DIREITO_CONSTITUCIONAL", ordem: 4 },
  DIREITO_ADMINISTRATIVO: { nome: "Direito Administrativo", codigo: "DIREITO_ADMINISTRATIVO", ordem: 5 },
  DIREITO_PENAL: { nome: "Direito Penal", codigo: "DIREITO_PENAL", ordem: 6 },
  DIREITO_PROCESSUAL_PENAL: { nome: "Direito Processual Penal", codigo: "DIREITO_PROCESSUAL_PENAL", ordem: 7 },
  LEGISLACAO_ESPECIAL: { nome: "Legislação Especial", codigo: "LEGISLACAO_ESPECIAL", ordem: 8 },
  ETICA_SERVICO_PUBLICO: { nome: "Ética no Serviço Público", codigo: "ETICA_SERVICO_PUBLICO", ordem: 9 },

  // Trânsito
  LEGISLACAO_TRANSITO: { nome: "Legislação de Trânsito", codigo: "LEGISLACAO_TRANSITO", ordem: 10 },

  // Military specific
  GEOGRAFIA: { nome: "Geografia", codigo: "GEOGRAFIA", ordem: 4 },
  HISTORIA: { nome: "História", codigo: "HISTORIA", ordem: 5 },
  FISICA: { nome: "Física", codigo: "FISICA", ordem: 6 },
  QUIMICA: { nome: "Química", codigo: "QUIMICA", ordem: 7 },
  INGLES: { nome: "Inglês", codigo: "INGLES", ordem: 8 },

  // Technical
  ATUALIDADES: { nome: "Atualidades", codigo: "ATUALIDADES", ordem: 10 },
  NOCOES_AVIACAO: { nome: "Noções de Aviação", codigo: "NOCOES_AVIACAO", ordem: 11 },
  ADMINISTRACAO: { nome: "Administração Pública", codigo: "ADMINISTRACAO", ordem: 10 },
};

// Define which materias each cargo type needs
const CARGO_MATERIAS_MAP: Record<string, string[]> = {
  // PF cargos (already have most, skip)
  // AGENTE_PF: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO", "MATEMATICA"],

  // Polícia Penal Federal
  POLICIAL_PPF: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO", "LEGISLACAO_ESPECIAL"],

  // Polícia Legislativa Federal
  POLICIAL_PLF: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],

  // ABIN
  OFICIAL_INTELIGENCIA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "LEGISLACAO_ESPECIAL", "ATUALIDADES", "INGLES"],
  OFICIAL_TECNICO: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ATUALIDADES", "INGLES"],
  AGENTE_ABIN: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "LEGISLACAO_ESPECIAL", "ATUALIDADES"],
  AGENTE_TECNICO: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ATUALIDADES"],

  // Exército
  ESPCEX: ["PORTUGUES", "MATEMATICA", "GEOGRAFIA", "HISTORIA", "FISICA", "QUIMICA", "INGLES"],
  ESA: ["PORTUGUES", "MATEMATICA", "GEOGRAFIA", "HISTORIA"],
  IME: ["PORTUGUES", "MATEMATICA", "FISICA", "QUIMICA", "INGLES"],
  ESFCEX: ["PORTUGUES", "MATEMATICA", "GEOGRAFIA", "HISTORIA", "INGLES"],
  OFICIAL_TEMP_EB: ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA"],

  // Marinha
  COLEGIO_NAVAL: ["PORTUGUES", "MATEMATICA", "FISICA", "QUIMICA", "INGLES"],
  ESCOLA_NAVAL: ["PORTUGUES", "MATEMATICA", "FISICA", "QUIMICA", "INGLES"],
  FUZILEIRO_NAVAL: ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA"],
  APRENDIZ_MARINHEIRO: ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA"],
  QT_MARINHA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO"],

  // FAB
  ITA: ["PORTUGUES", "MATEMATICA", "FISICA", "QUIMICA", "INGLES"],
  AFA: ["PORTUGUES", "MATEMATICA", "FISICA", "QUIMICA", "INGLES"],
  EPCAR: ["PORTUGUES", "MATEMATICA", "FISICA", "QUIMICA", "INGLES"],
  EEAR: ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "INGLES"],
  OFICIAL_TEMP_FAB: ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA"],

  // PFF (Polícia Ferroviária)
  POLICIAL_FERROVIARIO: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],

  // PJ CNJ (Polícia Judicial)
  POLICIAL_JUDICIAL: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  INSPETOR_PJ: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],

  // ANAC
  ESPECIALISTA_ANAC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "NOCOES_AVIACAO", "INGLES"],
  TECNICO_ANAC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "NOCOES_AVIACAO"],
  ANALISTA_ANAC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ADMINISTRACAO"],

  // Ministério da Defesa
  ANALISTA_DEFESA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ADMINISTRACAO", "ATUALIDADES"],
  TECNICO_DEFESA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ATUALIDADES"],

  // CPNU (materias comuns)
  CPNU_BLOCO1: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO2: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO3: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO4: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO5: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO6: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO7: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ADMINISTRACAO", "ETICA_SERVICO_PUBLICO"],
  CPNU_BLOCO8: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],

  // Polícia Científica
  PERITO_CRIMINAL: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  PERITO_LEGISTA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],
  PERITO_ODONTO: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],
  PAPILOSCOPISTA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],
  TEC_NECROPSIA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],
  AUX_PERICIA: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],

  // Guarda Portuária
  GUARDA_PORTUARIO: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],

  // PM
  SOLDADO_PM: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  CFO_PM: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO", "HISTORIA", "GEOGRAFIA"],

  // PC
  DELEGADO_PC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  INVESTIGADOR: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  ESCRIVAO_PC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  AGENTE_PC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  PERITO_PC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO"],
  PAPILOSCOPISTA_PC: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],

  // CBM
  SOLDADO_CBM: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO", "FISICA"],
  CFO_CBM: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO", "FISICA", "QUIMICA"],

  // PP Estadual
  AGENTE_PPE: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL", "ETICA_SERVICO_PUBLICO", "LEGISLACAO_ESPECIAL"],
  TECNICO_PPE: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "ETICA_SERVICO_PUBLICO"],

  // GM
  GUARDA_GM: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "ETICA_SERVICO_PUBLICO"],

  // PF additional cargos (add missing materias)
  ESCRIVAO_PF: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL"],
  DELEGADO_PF: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL", "DIREITO_PROCESSUAL_PENAL"],
  PAPILOSCOPISTA_PF: ["PORTUGUES", "RACIOCINIO_LOGICO", "INFORMATICA", "DIREITO_CONSTITUCIONAL", "DIREITO_ADMINISTRATIVO", "DIREITO_PENAL"],
};

async function seedAllCargoMaterias() {
  console.log("📚 Phase 3: Adding materias to all cargos...\n");

  try {
    let totalAdded = 0;
    let totalSkipped = 0;

    // Get all cargos
    const cargos = await db.execute(sql`
      SELECT cg.id, cg.codigo, cg.nome, c.sigla as concurso_sigla
      FROM cargos cg
      JOIN concursos c ON c.id = cg.concurso_id
      WHERE cg.is_active = true AND c.is_active = true
    `) as unknown as { id: string; codigo: string; nome: string; concurso_sigla: string }[];

    for (const cargo of cargos) {
      const materiasCodigos = CARGO_MATERIAS_MAP[cargo.codigo];

      if (!materiasCodigos) {
        console.log(`⚠️ No materia definition for: ${cargo.concurso_sigla} > ${cargo.codigo}`);
        continue;
      }

      let cargoAdded = 0;

      for (const materiaCodigo of materiasCodigos) {
        const materiaInfo = MATERIAS_BASE[materiaCodigo as keyof typeof MATERIAS_BASE];

        if (!materiaInfo) {
          console.log(`   ⚠️ Materia not found: ${materiaCodigo}`);
          continue;
        }

        // Check if already exists
        const existing = await db.execute(sql`
          SELECT id FROM cargo_materias
          WHERE cargo_id = ${cargo.id} AND codigo = ${materiaInfo.codigo}
        `);

        if (existing.length > 0) {
          totalSkipped++;
          continue;
        }

        // Insert
        await db.execute(sql`
          INSERT INTO cargo_materias (cargo_id, nome, codigo, ordem)
          VALUES (${cargo.id}, ${materiaInfo.nome}, ${materiaInfo.codigo}, ${materiaInfo.ordem})
        `);

        cargoAdded++;
        totalAdded++;
      }

      if (cargoAdded > 0) {
        console.log(`✅ ${cargo.concurso_sigla} > ${cargo.codigo}: ${cargoAdded} materias added`);
      }
    }

    console.log("\n" + "=".repeat(50));
    console.log(`📊 Total materias added: ${totalAdded}`);
    console.log(`⏭️ Already existing (skipped): ${totalSkipped}`);
    console.log("=".repeat(50));

  } catch (error) {
    console.error("❌ Error:", error);
    throw error;
  }
}

// Run
seedAllCargoMaterias()
  .then(() => {
    console.log("\n✅ Phase 3 completed!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("❌ Phase 3 failed:", error);
    process.exit(1);
  });
